name: dev-3
gcp-project: livingpackets-sandbox
region: europe-west3
type: dev
infrastructure:
  version: 0.0.1
  range-ip: 192.168.0.0/20
  range-ip-pod: 10.0.0.0/16
  range-ip-svc: 10.1.0.0/16
  range-plateform: 10.12.0.0/16
  cloudsql:
    version: MYSQL_5_7
    instance-type: "db-f1-micro"
    disk-size: 20
  gke:
    instance-type: n1-standard-1
    ips_whitelist:
    - 37.173.210.210/32
    max: 30
    min: 3
    preemptible: true
    version: 1.12
  dependancies:
    certmanager:
      enabled: true
      version: x
  namespaces:
  - gateways
  - webservices
  - monitoring
applications:
- documentation: http://swagger.io
  name: app_a
  version: 1.0.4
  namespace: webservices
- documentation: http://swagger.io
  name: app_a
  version: 2.0.3
  namespace: webservices
- documentation: http://swagger.io
  name: app_b
  version: 0.0.3
  namespace: gateways