name: prod
region: europe-west1
type: prod
gcp-project: slavayssiere-sandbox
infrastructure:
  range-ip: 10.0.16.0/20
  range-ip-master: 10.0.0.0/28
  range-ip-pod: 10.0.32.0/20
  range-ip-svc: 10.0.48.0/20
  range-plateform: 10.0.0.0/16
  cloudsql:
    disk-size: 20
    instance-type: db-f1-micro
    version: MYSQL_5_7
  dependancies:
    certmanager:
      enabled: true
      version: x
  gke:
    instance-type: n1-standard-1
    ips_whitelist:
    - 37.165.138.0
    max: 10
    min: 3
    preemptible: false
    version: 1.12
  namespaces:
  - gateways
  - webservices
  - monitoring
applications:
- documentation: http://swagger.io
  name: app-a
  namespace: webservices
  version: 1.0.4
- documentation: http://swagger.io
  name: app-c
  namespace: webservices
  version: 2.0.3
- documentation: http://swagger.io
  name: app-b
  namespace: gateways
  version: 0.0.3