apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: etcd-backend
  namespace: ingress-controller
  labels:
     app: etcd-backend
spec:
  size: 3
  version: "3.2.13"
  pod:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: etcd_cluster
              operator: In
              values: ["etcd-backend"]
          topologyKey: kubernetes.io/hostname
