apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-sm-public
  namespace: ingress-controller
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      release: public-ic
  endpoints:
  - port: metrics