// list with "gcloud services list"
resource "google_project_services" "project" {
  project = "${var.gcp-project}"

  services = [
    "container.googleapis.com",
    "datastore.googleapis.com",
    "pubsub.googleapis.com",
    "oslogin.googleapis.com",
    "cloudfunctions.googleapis.com",
    "compute.googleapis.com",
    "dns.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "servicenetworking.googleapis.com",
    "servicemanagement.googleapis.com",
    "serviceusage.googleapis.com",
    "sql-component.googleapis.com",
    "sqladmin.googleapis.com",
    "stackdriver.googleapis.com",
    "storage-api.googleapis.com",
    "storage-component.googleapis.com",
    "iamcredentials.googleapis.com",
    "iam.googleapis.com",
    "bigquery-json.googleapis.com",
    "containerregistry.googleapis.com",
    "firebase.googleapis.com",
    "firebasedynamiclinks.googleapis.com",
    "firebaserules.googleapis.com",
    "firebaseremoteconfig.googleapis.com",
    "firebasehosting.googleapis.com",
    "testing.googleapis.com",
    "appengine.googleapis.com",
    "googlecloudmessaging.googleapis.com",
    "clouddebugger.googleapis.com",
    "runtimeconfig.googleapis.com",
    "fcm.googleapis.com",
    "cloudapis.googleapis.com",
    "firestore.googleapis.com",
    "identitytoolkit.googleapis.com",
    "cloudtrace.googleapis.com",
    "securetoken.googleapis.com",
    "cloudresourcemanager.googleapis.com",
  ]
}
