apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: es-jaeger
  namespace: monitoring
spec:
  version: "6.3-v1"
  storageType: Durable
  authPlugin: "SearchGuard"
  enableSSL: false
  databaseSecret:
    secretName: jaeger-secrets
  topology:
    master:
      prefix: master
      replicas: 1
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    data:
      prefix: data
      replicas: 2
      storage:
        # storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    client:
      prefix: client
      replicas: 2
      storage:
        # storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi