apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: monitoring
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://es-jaeger.monitoring:9200
  ingress:
    enabled: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: private-ingress
spec:
  rules:
  - host: jaeger.dev-2.gcp-wescale.slavayssiere.fr
    http:
      paths:
      - backend:
          serviceName: simple-prod-query
          servicePort: 16686